### ISSUE TITLE
Feature request: add query string parsing for new chats

### ISSUE THREAD

**Issue by wgj** [sabeechen/homelab-gpt#4]
Often, I like to use GPT as an alternative to a search engine. Typically, when I use a search engine, I'm typing my query into my brower's omnibox. If homelab-gpt had a query string "interface", I could add it as another search engine in my browser.

I'm not sure what homelab-gpt should do in this context, but maybe an enphemeral "new chat", so the "unsaved chat" doesn't get prohibitively expensive for small questions.

**Comment by sabeechen** [comment]
That's a solid idea.  I'll need to rejigger a few things to make it work right though

**Comment by sabeechen** [comment]
Its done, hard refresh the page and you should be able to install it as a standard search engine.
